export type ProductStatus = "publicado" | "oculto"

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  status: ProductStatus
  productCount?: number
}

export interface Product {
  id: string
  code: string
  name: string
  description: string
  price: number
  category: string
  categorySlug: string
  unit: string
  image: string
  status: ProductStatus
}

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Salsas y Condimentos",
    slug: "salsas-y-condimentos",
    description: "Salsas importadas y condimentos para cocina oriental profesional.",
    status: "publicado",
  },
  {
    id: "cat-2",
    name: "Fideos y Arroces",
    slug: "fideos-y-arroces",
    description: "Arroces premium para sushi y fideos para wok en presentaciones mayoristas.",
    status: "publicado",
  },
  {
    id: "cat-3",
    name: "Pescados y Mariscos",
    slug: "pescados-y-mariscos",
    description: "Pescados frescos y congelados seleccionados para uso gastronómico.",
    status: "publicado",
  },
  {
    id: "cat-4",
    name: "Algas y Productos Secos",
    slug: "algas-y-productos-secos",
    description: "Algas nori, sésamo y productos secos para sushi.",
    status: "publicado",
  },
  {
    id: "cat-5",
    name: "Conservas y Almacén",
    slug: "conservas-y-almacen",
    description: "Insumos mayoristas de almacén para cocina profesional.",
    status: "publicado",
  },
  {
    id: "cat-6",
    name: "Frescos y Congelados",
    slug: "frescos-y-congelados",
    description: "Productos refrigerados y congelados para la dinámica diaria de tu cocina.",
    status: "publicado",
  },
  {
    id: "cat-7",
    name: "Papelería y Packaging",
    slug: "papeleria-y-packaging",
    description: "Descartables y packaging para delivery y salón.",
    status: "oculto",
  },
]

export const products: Product[] = [
  // Salsas y Condimentos
  {
    id: "prod-1",
    code: "SC-001",
    name: "Salsa de Soja Fumeiga",
    description: "bidón x 5 lts — master 4 bidones",
    price: 18500,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Bidón x 5 lts",
    image: "/precio-salsa-soja.png",
    status: "publicado",
  },
  {
    id: "prod-2",
    code: "SC-002",
    name: "Salsa de Soja Sachet Fumeiga",
    description: "sachet x 10 gr — caja x 500 u",
    price: 12800,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Caja x 500u (10g c/u)",
    image: "/sachet.jpg",
    status: "publicado",
  },
  {
    id: "prod-3",
    code: "SC-003",
    name: "Salsa Agridulce Fumeiga",
    description: "botella x 2 lts — master 6 botellas",
    price: 9400,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Botella x 2 lts",
    image: "/agridulce.jpg",
    status: "publicado",
  },
  {
    id: "prod-4",
    code: "SC-004",
    name: "Salsa de Ostras Haday",
    description: "pote x 2,27 kg — master 6 potes",
    price: 14200,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Pote x 2,27 KG",
    image: "/ostras.png",
    status: "publicado",
  },
  {
    id: "prod-5",
    code: "SC-005",
    name: "Siracha Toung Ot",
    description: "frasco x 793 gr — master 12 frascos",
    price: 7600,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Frasco x 793 gr",
    image: "/siracha.png",
    status: "publicado",
  },
  {
    id: "prod-6",
    code: "SC-006",
    name: "Aceite de Sésamo Ann",
    description: "botella x 1 lt — master 12 botellas",
    price: 11300,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Botella x 1 lt",
    image: "/aceite-sesamo.jpg",
    status: "publicado",
  },
  {
    id: "prod-7",
    code: "SC-007",
    name: "Mirim Shi Quian",
    description: "botella x 500 ml — master 12 botellas",
    price: 8900,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Botella x 500 ml",
    image: "/mirim.jpg",
    status: "publicado",
  },
  {
    id: "prod-8",
    code: "SC-008",
    name: "Wasabi Powder",
    description: "bolsa x 1 kg — master 10 bolsas",
    price: 16800,
    category: "Salsas y Condimentos",
    categorySlug: "salsas-y-condimentos",
    unit: "Bolsa x 1 KG",
    image: "/precio-wasabi.png",
    status: "publicado",
  },

  // Fideos y Arroces
  {
    id: "prod-9",
    code: "FA-001",
    name: "Arroz Fortuna 00000 Fumeiga",
    description: "bolsa x 30 kg — master 1 bolsa",
    price: 52000,
    category: "Fideos y Arroces",
    categorySlug: "fideos-y-arroces",
    unit: "Bolsa x 30 KG",
    image: "/precio-arroz.png",
    status: "publicado",
  },
  {
    id: "prod-10",
    code: "FA-002",
    name: "Arroz Largo Fino para Wok",
    description: "bolsa x 30 kg — master 1 bolsa",
    price: 38500,
    category: "Fideos y Arroces",
    categorySlug: "fideos-y-arroces",
    unit: "Bolsa x 30 KG",
    image: "/arroz-largo.jpg",
    status: "publicado",
  },
  {
    id: "prod-11",
    code: "FA-003",
    name: "Fideos de Arroz Fino",
    description: "paquete x 400 gr — master 30 paquetes",
    price: 4200,
    category: "Fideos y Arroces",
    categorySlug: "fideos-y-arroces",
    unit: "Paquete x 400 gr",
    image: "/fideos.jpg",
    status: "publicado",
  },
  {
    id: "prod-12",
    code: "FA-004",
    name: "Blister de Soja Fumeiga",
    description: "blister — caja x 180 u",
    price: 9800,
    category: "Fideos y Arroces",
    categorySlug: "fideos-y-arroces",
    unit: "Caja x 180 u",
    image: "/blister.jpg",
    status: "publicado",
  },
  {
    id: "prod-13",
    code: "FA-005",
    name: "Panko Japanese Style Blanco",
    description: "bolsa x 1 kg — master 10 bolsas",
    price: 5600,
    category: "Fideos y Arroces",
    categorySlug: "fideos-y-arroces",
    unit: "Bolsa x 1 KG",
    image: "/panko-blanco.jpg",
    status: "publicado",
  },

  // Pescados y Mariscos
  {
    id: "prod-14",
    code: "PM-001",
    name: "Salmón Entero Fresco Premium Salar",
    description: "entero fresco — presentación 4–5 kg",
    price: 24500,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "x KG",
    image: "/precio-salmon.png",
    status: "publicado",
  },
  {
    id: "prod-15",
    code: "PM-002",
    name: "Cola de Langostino IQF",
    description: "iqf pelado — bolsa x 2 kg — master 5 kg",
    price: 18900,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "x KG",
    image: "/precio-langostino.png",
    status: "publicado",
  },
  {
    id: "prod-16",
    code: "PM-003",
    name: "Kanikama Largo Santa Elena",
    description: "paquete x 600 gr — master 10 paquetes",
    price: 8700,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "Paquete x 600 gr",
    image: "/kanikama.jpg",
    status: "publicado",
  },
  {
    id: "prod-17",
    code: "PM-004",
    name: "Caviar Rojo Boken",
    description: "frasco x 320 gr — master 10 frascos",
    price: 13400,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "Frasco x 320 gr",
    image: "/caviar-rojo.jpg",
    status: "publicado",
  },
  {
    id: "prod-18",
    code: "PM-005",
    name: "Caviar Negro Boken",
    description: "frasco x 320 gr — master 10 frascos",
    price: 13400,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "Frasco x 320 gr",
    image: "/caviar-negro.jpg",
    status: "publicado",
  },
  {
    id: "prod-19",
    code: "PM-006",
    name: "Atún Rojo en Cubos",
    description: "cubos — trozos x 500 gr — master 5 kg",
    price: 31200,
    category: "Pescados y Mariscos",
    categorySlug: "pescados-y-mariscos",
    unit: "x KG (trozos de 500 gr)",
    image: "/atun-cubos.jpeg",
    status: "publicado",
  },

  // Algas y Productos Secos
  {
    id: "prod-20",
    code: "AP-001",
    name: "Algas Nori Yaki Paquete Blanco",
    description: "paquete blanco x 100 láminas — master 10 paquetes",
    price: 22600,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "Paquete x 100 láminas",
    image: "/precio-algas.png",
    status: "publicado",
  },
  {
    id: "prod-21",
    code: "AP-002",
    name: "Algas Nori Yamagataya Paquete Rojo",
    description: "paquete rojo x 100 láminas — master 10 paquetes",
    price: 19800,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "Paquete x 100 láminas",
    image: "/algas-2.jpg",
    status: "publicado",
  },
  {
    id: "prod-22",
    code: "AP-003",
    name: "Sésamo Blanco",
    description: "presentación x 1 kg — master 10 kg",
    price: 6800,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "x KG",
    image: "/precio-sesamo.png",
    status: "publicado",
  },
  {
    id: "prod-23",
    code: "AP-004",
    name: "Sésamo Negro",
    description: "presentación x 1 kg — master 10 kg",
    price: 7200,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "x KG",
    image: "/sesamo-negro.jpg",
    status: "publicado",
  },
  {
    id: "prod-24",
    code: "AP-005",
    name: "Jengibre en Hojas Gari Natural",
    description: "pote x 1 kg — master 12 potes",
    price: 9100,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "Pote x 1 KG",
    image: "/jengibre-natural.jpg",
    status: "publicado",
  },
  {
    id: "prod-25",
    code: "AP-006",
    name: "Hondashi",
    description: "bolsa x 500 gr — master 12 bolsas",
    price: 11500,
    category: "Algas y Productos Secos",
    categorySlug: "algas-y-productos-secos",
    unit: "Bolsa x 500 gr",
    image: "/hondashi.jpg",
    status: "publicado",
  },

  // Conservas y Almacén
  {
    id: "prod-26",
    code: "CA-001",
    name: "Aceite Girasol Caracas",
    description: "garrafa x 8,8 lts — master 2 garrafas",
    price: 29400,
    category: "Conservas y Almacén",
    categorySlug: "conservas-y-almacen",
    unit: "Garrafa x 8,8 lts",
    image: "/aceite-girasol.jpg",
    status: "publicado",
  },
  {
    id: "prod-27",
    code: "CA-002",
    name: "Vinagre de Alcohol Los Emprendedores",
    description: "bidón x 5 lts — master 4 bidones",
    price: 6300,
    category: "Conservas y Almacén",
    categorySlug: "conservas-y-almacen",
    unit: "Bidón x 5 lts",
    image: "/precio-vinagre.png",
    status: "publicado",
  },
  {
    id: "prod-28",
    code: "CA-003",
    name: "Mayonesa Natura",
    description: "balde x 3 kg — master 4 baldes",
    price: 15600,
    category: "Conservas y Almacén",
    categorySlug: "conservas-y-almacen",
    unit: "Balde x 3 KG",
    image: "/mayo.jpg",
    status: "publicado",
  },
  {
    id: "prod-29",
    code: "CA-004",
    name: "Azúcar Refinada Chango",
    description: "bolsa x 1 kg — master 25 kg",
    price: 2800,
    category: "Conservas y Almacén",
    categorySlug: "conservas-y-almacen",
    unit: "Bolsa x 1 KG",
    image: "/azucarrefinada.jpeg",
    status: "publicado",
  },
  {
    id: "prod-30",
    code: "CA-005",
    name: "Queso Finlandia Sachet Serenísima",
    description: "sachet x 2 kg con manga — master 6 sachets",
    price: 18900,
    category: "Conservas y Almacén",
    categorySlug: "conservas-y-almacen",
    unit: "Sachet x 2 KG c/manga",
    image: "/finlandia.jpg",
    status: "publicado",
  },

  // Frescos y Congelados
  {
    id: "prod-31",
    code: "FC-001",
    name: "Empanaditas Chinas Harumaki",
    description: "pack x 50 u — master 1 pack",
    price: 7400,
    category: "Frescos y Congelados",
    categorySlug: "frescos-y-congelados",
    unit: "Pack x 50 u",
    image: "/empanaditas.jpg",
    status: "publicado",
  },
  {
    id: "prod-32",
    code: "FC-002",
    name: "Dumplings de Cerdo y Choclo",
    description: "pack x 24 u — master 1 pack",
    price: 8900,
    category: "Frescos y Congelados",
    categorySlug: "frescos-y-congelados",
    unit: "Pack x 24 u",
    image: "/dumplings.jpg",
    status: "publicado",
  },
  {
    id: "prod-33",
    code: "FC-003",
    name: "Pechuga de Pollo Deshuesada",
    description: "presentación x 2 kg — master 15 kg",
    price: 11200,
    category: "Frescos y Congelados",
    categorySlug: "frescos-y-congelados",
    unit: "x KG (presentación x 15 KG)",
    image: "/pechuga.jpg",
    status: "publicado",
  },
  {
    id: "prod-34",
    code: "FC-004",
    name: "Mejillón Pelado Chileno IQF",
    description: "iqf pelado — bolsa x 1 kg — master 10 kg",
    price: 14600,
    category: "Frescos y Congelados",
    categorySlug: "frescos-y-congelados",
    unit: "x KG",
    image: "/mejillon.jpg",
    status: "publicado",
  },

  // Papelería y Packaging
  {
    id: "prod-35",
    code: "PP-001",
    name: "Bandeja de Sushi Grande Bandex",
    description: "pack x 200 u con tapa — master 1 pack",
    price: 18400,
    category: "Papelería y Packaging",
    categorySlug: "papeleria-y-packaging",
    unit: "Pack x 200 u con tapa",
    image: "/bandeja-grande.webp",
    status: "oculto",
  },
  {
    id: "prod-36",
    code: "PP-002",
    name: "Palitos Chinos con Funda",
    description: "pack x 100 u con funda — master 10 packs",
    price: 5600,
    category: "Papelería y Packaging",
    categorySlug: "papeleria-y-packaging",
    unit: "Pack x 100 u",
    image: "/palillos.jpg",
    status: "oculto",
  },
  {
    id: "prod-37",
    code: "PP-003",
    name: "Esterillas para Sushi",
    description: "27x27 cm — unidad",
    price: 3200,
    category: "Papelería y Packaging",
    categorySlug: "papeleria-y-packaging",
    unit: "x 1 u (27x27 cm)",
    image: "/esterillas.webp",
    status: "oculto",
  },
  {
    id: "prod-38",
    code: "PP-004",
    name: "Pote Salcero 55cc",
    description: "pack x 1300 u con tapa — master 1 pack",
    price: 6800,
    category: "Papelería y Packaging",
    categorySlug: "papeleria-y-packaging",
    unit: "Pack x 1300 u con tapa",
    image: "/pote.jpg",
    status: "oculto",
  },
]
